# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\"\xbd\x01\n\x10\x45ventEnvelopeMsg\x12\x13\n\x0btarget_node\x18\x01 \x01(\t\x12\x16\n\x0etarget_simproc\x18\x02 \x01(\t\x12\r\n\x05\x65poch\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12/\n\x07headers\x18\x05 \x03(\x0b\x32\x1e.EventEnvelopeMsg.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"s\n\x12PromiseEnvelopeMsg\x12\x13\n\x0btarget_node\x18\x01 \x01(\t\x12\x16\n\x0etarget_simproc\x18\x02 \x01(\t\x12\r\n\x05seqnr\x18\x03 \x01(\x03\x12\r\n\x05\x65poch\x18\x04 \x01(\x01\x12\x12\n\nnum_events\x18\x05 \x01(\x05\"\x1f\n\x0cTransportAck\x12\x0f\n\x07message\x18\x01 \x01(\t2u\n\x0e\x44iscoTransport\x12\x30\n\nSendEvents\x12\x11.EventEnvelopeMsg\x1a\r.TransportAck(\x01\x12\x31\n\x0bSendPromise\x12\x13.PromiseEnvelopeMsg\x1a\r.TransportAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _EVENTENVELOPEMSG_HEADERSENTRY._options = None
  _EVENTENVELOPEMSG_HEADERSENTRY._serialized_options = b'8\001'
  _globals['_EVENTENVELOPEMSG']._serialized_start=20
  _globals['_EVENTENVELOPEMSG']._serialized_end=209
  _globals['_EVENTENVELOPEMSG_HEADERSENTRY']._serialized_start=163
  _globals['_EVENTENVELOPEMSG_HEADERSENTRY']._serialized_end=209
  _globals['_PROMISEENVELOPEMSG']._serialized_start=211
  _globals['_PROMISEENVELOPEMSG']._serialized_end=326
  _globals['_TRANSPORTACK']._serialized_start=328
  _globals['_TRANSPORTACK']._serialized_end=359
  _globals['_DISCOTRANSPORT']._serialized_start=361
  _globals['_DISCOTRANSPORT']._serialized_end=478
# @@protoc_insertion_point(module_scope)
