# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import disco.transports.proto.transport_pb2 as transport__pb2


class DiscoTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvents = channel.stream_unary(
                '/DiscoTransport/SendEvents',
                request_serializer=transport__pb2.EventEnvelopeMsg.SerializeToString,
                response_deserializer=transport__pb2.TransportAck.FromString,
                )
        self.SendPromise = channel.unary_unary(
                '/DiscoTransport/SendPromise',
                request_serializer=transport__pb2.PromiseEnvelopeMsg.SerializeToString,
                response_deserializer=transport__pb2.TransportAck.FromString,
                )


class DiscoTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEvents(self, request_iterator, context):
        """Events: potentially large and frequent. Use a client-streaming RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPromise(self, request, context):
        """Promises: always small. Use a unary RPC for better latency and observability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.SendEvents,
                    request_deserializer=transport__pb2.EventEnvelopeMsg.FromString,
                    response_serializer=transport__pb2.TransportAck.SerializeToString,
            ),
            'SendPromise': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPromise,
                    request_deserializer=transport__pb2.PromiseEnvelopeMsg.FromString,
                    response_serializer=transport__pb2.TransportAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DiscoTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/DiscoTransport/SendEvents',
            transport__pb2.EventEnvelopeMsg.SerializeToString,
            transport__pb2.TransportAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPromise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DiscoTransport/SendPromise',
            transport__pb2.PromiseEnvelopeMsg.SerializeToString,
            transport__pb2.TransportAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
